### ISSUE TITLE
500 Internal Server Error when tried to login into amadaa without user credentials 

### ISSUE THREAD

**Issue by BorderITS** [borderitsolutions/amadaa-server#32]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/nelson/Git/amadaa-server/ENV/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/nelson/Git/amadaa-server/ENV/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/nelson/Git/amadaa-server/ENV/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/nelson/Git/amadaa-server/amadaa/auth.py", line 41, in login
    uid = authenticate(username, password)
  File "/home/nelson/Git/amadaa-server/amadaa/auth.py", line 15, in authenticate
    hashed_pw = user[1]
TypeError: 'NoneType' object is not subscriptable

**Comment by lcabrini** [comment]
This is a bug, not a user story. Changing the label.

**Comment by BorderITS** [comment]
I forgot, thanks Lorenzo.

**Comment by lcabrini** [comment]
Works for me. What credentials did you provide?

**Comment by BorderITS** [comment]
After I started amadaa  in the browser I typed in the localhost  where u will enter admin and changeme  as user credentials I didn't and hit enter at least it should have say something to refer the user the enter their credentials

**Comment by lcabrini** [comment]
Confirmed. Happens for me as well. Will look into it.

**Comment by BorderITS** [comment]
okay then let's try fix this bug for good

**Comment by BorderITS** [comment]
bug is fixed , now when you did not enter user credentials amadaa will prompt you for authentication

**Comment by BorderITS** [comment]
Login now requires user credential before you can access
